### ISSUE TITLE
One query failes; Type mismatch: expected Path but was String

### ISSUE THREAD

**Issue by motey** [covidgraph/data_clinical-trials-gov#3]
``` 
Run query 
'
 call apoc.load.json('https://clinicaltrials.gov/api/query/study_fields?expr=COVID+AND+AREA%5BStudyType%5DObservational&fields=NCTId&fmt=json&max_rnk=1000') yield value
with value.StudyFieldsResponse.NStudiesFound as NStudies, RANGE(0,(value.StudyFieldsResponse.NStudiesFound/1000)) as nloop
UNWIND nloop as i
with range(1+1000*i,1000+1000*i,999) as RANGES
with RANGES, RANGES[1] as urange, RANGES[0] as lrange
call apoc.load.json('https://clinicaltrials.gov/api/query/study_fields?expr=COVID+AND+AREA%5BStudyType%5DObservational&fields=NCTId,Gender,GenderBased,GenderDescription,MinimumAge,MaximumAge,HealthyVolunteers,StudyPopulation,SamplingMethod,EligibilityCriteria&min_rnk='+lrange+'&max_rnk='+urange+'&fmt=json') yield value
with value.StudyFieldsResponse.StudyFields as coll unwind coll as study_metadata
UNWIND study_metadata.NCTId as Id
match(ct:ClinicalTrial{NCTId:Id})
UNWIND study_metadata.EligibilityCriteria as EligibilityCriteria
with study_metadata, ct, split(replace(replace(trim(substring(EligibilityCriteria,length(split(EligibilityCriteria,"Exclusion")[0]),size(EligibilityCriteria))),'\n','#'),'##','#'),'#') as Exclusion,
split(replace(replace(trim(substring(EligibilityCriteria,0,length(split(EligibilityCriteria,"Exclusion")[0]))),'\n','#'),'##','#'),'#') as Inclusion
with study_metadata, ct, Inclusion, Exclusion, RANGE(1,size(Inclusion)-1) as nincl
FOREACH(i in nincl |
MERGE(ct)-[:HAS_INCLUSION_CRITERIA]->(incl:InclusionCriteria{criteria:Inclusion[i]}))
with study_metadata, ct, Inclusion, Exclusion, RANGE(1,size(Exclusion)-1) as nexcl
FOREACH(i in nexcl |
MERGE(ct)-[:HAS_EXCLUSION_CRITERIA]->(excl:ExclusionCriteria{criteria:Exclusion[i]}))
'
Traceback (most recent call last):
  File "/home/tim/Repos/github.com/covidgraph/data_clinical-trials-gov/dataloader/main.py", line 100, in <module>
    tx.run(q)
  File "/home/tim/.local/lib/python3.8/site-packages/py2neo/database/work.py", line 119, in run
    result = self._connector.run_in_tx(self._transaction, cypher, parameters, hydrant)
  File "/home/tim/.local/lib/python3.8/site-packages/py2neo/client/__init__.py", line 1007, in run_in_tx
    cx.sync(result)  # TODO: avoid sync on every tx.run
  File "/home/tim/.local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 321, in sync
    self._audit(result)
  File "/home/tim/.local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 420, in _audit
    task.audit()
  File "/home/tim/.local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 609, in audit
    item.audit()
  File "/home/tim/.local/lib/python3.8/site-packages/py2neo/client/bolt.py", line 781, in audit
    raise self._failure
py2neo.database.work.ClientError: [Statement.SyntaxError] Type mismatch: expected Path but was String (line 12, column 130 (offset: 1076))
"with study_metadata, ct, split(replace(replace(trim(substring(EligibilityCriteria,length(split(EligibilityCriteria,"Exclusion")[0]),size(EligibilityCriteria))),'\n','#'),'##','#'),'#') as Exclusion,"
                                                                                                                                  ^
```

**Comment by KirstenLangendorf** [comment]
Hi Tim,

I am attending a virtual conference tonight. Can have a look at it tomorrow morning.

Kr Kirsten
